services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12-bullseye
        USER_UID: 1000
        USER_GID: 1000
    env_file:
      - ./api/.env
    
    command: sleep infinity
    links: 
      - fe
    volumes:
      - .:/workspace:cached
    user: vscode
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        VARIANT: 20-bullseye
        USER_UID: 1000
        USER_GID: 1000
    env_file:
      - ./fe/.env
    command: sleep infinity
    volumes:
      - .:/workspace:cached