services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.12-bullseye
        USER_UID: 1000
        USER_GID: 1000        
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    user: vscode    
    env_file:
      - ../.env
